#!/usr/bin/bash

t_freeze=-5
t_cold=0
t_cool=5
t_norm=15
t_warm=20
t_nice=25
t_hot=35


data=$(/usr/bin/curl --silent -G 'http://192.168.4.112:8086/query?db=weather' --data-urlencode 'q=SELECT last("temperature") FROM "weather" WHERE time > now() - 10m')
if [[ $? -ne 0 ]]; then exit $?; fi
result=$(echo $data | /usr/bin/jq ".results[0].series[0].values[0][1]")
if [[ $? -ne 0 ]]; then exit $?; fi


printf "%.1f °C\n" $result

if (( $(echo "$result < $t_freeze" | /usr/bin/bc -l) )); then
	printf "#3388FF\n";
	printf "#3388FF\n";
elif (( $(echo "$result < $t_cold" | /usr/bin/bc -l) )); then
	printf "#33CCFF\n";
	printf "#33CCFF\n";
elif (( $(echo "$result < $t_cool" | /usr/bin/bc -l) )); then
	printf "#33FFCC\n";
	printf "#33FFCC\n";
elif (( $(echo "$result < $t_norm" | /usr/bin/bc -l) )); then
	printf "#CCFFCC\n";
	printf "#CCFFCC\n";
elif (( $(echo "$result < $t_warm" | /usr/bin/bc -l) )); then
	printf "#CCFF33\n";
	printf "#CCFF33\n";
elif (( $(echo "$result < $t_nice" | /usr/bin/bc -l) )); then
	printf "#FFCC33\n";
	printf "#FFCC33\n";
elif (( $(echo "$result < $t_hot" | /usr/bin/bc -l) )); then
	printf "#FF8833\n";
	printf "#FF8833\n";
else
	printf "#FF5500\n";
	printf "#FF5500\n";
fi
